# env is incoming, using defaults fallbacks for now
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/sayless}
server.port=${SERVER_PORT:8081}\

jwt.secret=${JWT_SECRET:default-secret}
jwt.expiration-ms=${JWT_EXPIRATION:86400000}