spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/sayless}
server.port=${SERVER_PORT:8083}
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION:86400000}
logging.level.root=INFO
auth.service.url=http://localhost:8081
cors.allowed-origins=http://localhost:5173,http://localhost:3000
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=friendRequestSent:com.sayless.friend.event.FriendRequestSentEvent,friendRequestAccepted:com.sayless.friend.event.FriendRequestAcceptedEvent
