apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 40
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: CORS_ALLOWED_ORIGINS
              value: http://sayless.local
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MONGO_URI
