apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: gateway-service:latest
          imagePullPolicy: Never
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service:8081/auth
            - name: TASKS_SERVICE_URL
              value: http://task-service:8082/tasks
            - name: FRIENDS_SERVICE_URL
              value: http://friend-service:8083/friends
            - name: AI_SERVICE_URL
              value: http://ai-service:8000
            - name: USERS_SERVICE_URL
              value: http://auth-service:8081/users
            - name: NOTIFICATIONS_SERVICE_URL
              value: http://notification-service:8085/notifications
            - name: CORS_ALLOWED_ORIGINS
              value: http://sayless.local
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET